# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  toxify:
    docker:
      - image: themattrix/tox
    steps:
      - checkout
      - run:
          name: Run tests in supported Python versions
          command: |
            pip install tox tox-pyenv
            pyenv local 3.5.3 3.6.0 3.7.0 3.8.0
            tox
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

workflows:
  version: 2

  shublang:
    jobs:
      - toxify
      - build
