# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      # Run tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            py.test
            
      - run:
          command: |
            set -x
            sudo pip install awscli
            sed -i "s/^__VERSION__ = .*/__VERSION__ = \'git.${CIRCLE_BRANCH/\//\\/}.${CIRCLE_SHA1:0:7}\'/" setup.py
            sudo python setup.py sdist bdist_wheel
            aws s3 sync dist/ s3://pkgrepo.scrapinghub.com/python/packages/
            tags=$(git tag -l --points-at $CIRCLE_SHA1)
            for tag in $tags; do
              sed -i "s/^__VERSION__ = .*/__VERSION__ = \'$tag\'/" setup.py
              sudo python setup.py sdist bdist_wheel
              aws s3 sync dist/ s3://pkgrepo.scrapinghub.com/python/packages/
            done
